site_name: "PhotoView for Jetpack Compose"
site_description: "Alternative implementation of PhotoView for Jetpack Compose that supports zooming, by various touch gestures."
site_author: "fornewid"
remote_branch: gh-pages

# Repository
repo_name: fornewid/photo-compose
repo_url: https://github.com/fornewid/photo-compose

# Navigation
nav:
  - "Overview": index.md
  - "API Docs": api/index.html

# Configuration
theme:
  name: material
  language: "en"
  palette:
    primary: green
    accent: green
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
